### PR TITLE
fix: display the province field in registration form

### PR DESCRIPTION
**Pull request by MaferMazu**
Added `self.fields['province'].required = True` in forms.py to display the province field in registration form

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Did you find out why this happens?

**Comment by MaferMazu** [comment]
I don't know, yesterday I was on it and I didn't get anything, @MoisesGSalas  told me that when he has a chance he will check it.

**Review by MoisesGSalas — CHANGES_REQUESTED** [review]
I'm still not quite sure how this worked in Ironwood since the default behavior is to set the field as optional when `blank=True`.
 
The field is added to the form [with this function](https://github.com/edx/edx-platform/blob/07fa54703ecf78da507b29cad8b3393a55731be9/openedx/core/djangoapps/user_api/helpers.py#L136) and it's [called here](https://github.com/edx/edx-platform/blob/07fa54703ecf78da507b29cad8b3393a55731be9/openedx/core/djangoapps/user_authn/views/registration_form.py#L404).

What you can do is: instead of changing the model and the migration change the field on [form.py](https://github.com/eduNEXT/campusromero-openedx-extensions/blob/master/campusromero_openedx_extensions/custom_registration_form/forms.py#L45). Add a new line that has `self.fields['province'].required = True`

**Comment by MaferMazu** [comment]
Thanks a lot @MoisesGSalas

**Review by MoisesGSalas — APPROVED** [review]

**Review by mariajgrimaldi — APPROVED** [review]

**Pull request merged**
