### PR TITLE
Add locale folder and translations.

### PR DESCRIPTION
**Pull request by Squirrel18**
## Description:

This PR adds the locale folder and 'make' commands to extract and compile translations files for es_419 locale language.

## Reviewers: 

- [ ] @jfavellar90 
- [ ] @Alec4r

### CODE REVIEW

**Comment by jfavellar90** [comment]
@Squirrel18 please take a look on these changes as soon as you can, I added a function on common settings to replace the behavior of the standard LOCALE_PATHS which is a function. In this way we don't to add anything on the platform side.

**Comment by jfavellar90** [comment]
@Squirrel18 translations are already working

**Comment by Squirrel18** [comment]
@jfavellar90 It is not neccesary to add a function to get the LOCALE_PATHS, is just neccesary that the locale folder is inside of the campusromero_openedx_extensions folder.
I tested this without adding anything to get LOCALE_PATH and works as expected, so I didn't add anything to edx-platform to get the LOCALE_PATH of the plugin.

**Comment by jfavellar90** [comment]
@Squirrel18 for some reason it did not work that way for me. let me just double chek that

**Comment by jfavellar90** [comment]
@Squirrel18 you were totally right, I did not need that (lost time), well I think this PR is ready, please help me with a final review. cc @Alec4r

**Comment by Alec4r** [comment]
@Squirrel18 @jfavellar90  I see it well.

**Pull request merged**
